docs/DeveloperGuide.md
Update use cases in DG to ConnectS
=> Add DG use cases

src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java
Changed the function of help to display in the message screen, while retaining the function of the help button at the top of the app, to provide a link to the UG.
Added MESSAGE_USAGE, for some commands which do not have that. It is the same field which is used when the user incorrectly uses a command.
=> Update view help

src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/TelegramHandle.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/ModTutGroupTest.java, src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/NameTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/TelegramHandleTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
- Mostly updating test files to support the recently updated Person model.
- Added 2 new test files: ModTutGroupTest.java and TelegramHandleTest.java
- TelegramHandleTest is commented out due to failing test cases regarding validity of telegram handle
Telegram handle with less than 5 characters was considered valid
Capital letters is not accepted as valid (It should be valid right?)
Update: Updated REGEX in TelegramHandle class and integrated the test
closes #51
=> Update test files in model.person

src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Remove test comments

src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/model/person/PersonTest.java
If a new contact has the same telegram or same email as other people in the contact list, then will get a duplicate message: "This person already exists in the address book"
=> Check same telegram and email

build.gradle, src/main/resources/view/MainWindow.fxml
=> Update App title and file name

src/test/java/seedu/address/logic/LogicManagerTest.java
=> Reinstate LogicManagerTest

src/main/java/seedu/address/ui/HelpWindow.java
=> Change help window url to point to ConnectS UG

src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> Rename variable to be camelCase

src/main/java/seedu/address/MainApp.java
=> Change version to 1.3

src/main/java/seedu/address/model/person/ModTutGroup.java, src/main/java/seedu/address/model/person/Module.java, src/main/java/seedu/address/model/person/Tutorial.java
Add module and tutorial field into ModTutGroup class.
=> Add mod, Add Tut

src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/SortCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
- Add Sort functionality
- Update HelpCommand to include sort
- Update test cases for sort
=> Add Sort Command

src/main/java/seedu/address/model/person/ModTutGroup.java, src/main/java/seedu/address/model/person/Tutorial.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ModuleTabPane.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/main/java/seedu/address/ui/TutorialTabPane.java, src/main/java/seedu/address/ui/UiManager.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ModuleTabPane.fxml, src/main/resources/view/ResultDisplay.fxml, src/main/resources/view/TutorialTabPane.fxml
=> Update GUI to match User Guide

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/PinCommand.java, src/main/java/seedu/address/logic/commands/UnpinCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/PinCommandParser.java, src/main/java/seedu/address/logic/parser/UnpinCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/person/exceptions/PersonMustBeSameException.java, src/main/java/seedu/address/model/person/exceptions/WrongPinStatusException.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
*Changes:*
- Add isPin field to Person as a boolean
- Add Pin and Unpin commands and functionality
- Update Help
*How it works now:*
- Pin command will put a person to the top of the list while Unpin will bring a person to the bottom of the list
- Sort command will only sort Persons that are not pinned
Perhaps a future improvement can be to make the Pinned Persons obvious by making their Person Card a different color (?)
=> Add Pin & Unpin

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ViewCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ModuleTabPane.java, src/main/java/seedu/address/ui/TutorialTabPane.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java
Closes #148 
Closes #147 
Closes #146 
Closes #145
=> Fix delete command behaviour

src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml
=> Reimplement tags to ui

src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml
=> Add light blue border for pinned contact

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Index will now refer to current view
Closes #190
=> Fix delete command indexing on different views

src/main/java/seedu/address/logic/commands/FindCommand.java
Find command in tab view will now switch to the tab of the persons first module tutorial group
Closes #172
=> Fix find command behaviour

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/ModTutGroup.java, src/main/java/seedu/address/model/person/Module.java, src/main/java/seedu/address/model/person/Tutorial.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/ModTutGroupTest.java, src/test/java/seedu/address/model/person/ModuleTest.java, src/test/java/seedu/address/model/person/TutorialTest.java
Convert mod-tut string to uppercase in ParserUtil.parseModTutGroup
Added assertions in ModTutGroup, Module and Tutorial class to ensure uppercase
=> Capitalize ModTutGroup

src/main/java/seedu/address/logic/commands/AddCommand.java
=> Fix add command message usage text

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteModCommand.java, src/main/java/seedu/address/logic/commands/DeleteModTutCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/ModTutGroup.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/java/seedu/address/storage/JsonAdaptedModTutGroup.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/logic/commands/DeleteModCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteModTutCommandTest.java, src/test/java/seedu/address/testutil/PersonUtil.java
Fix the delete command behaviour where tabs are removed when there are no contacts under it
Also, changed the output of the person when adding/editing/deleting/pinning/unpinning persons
OLD:
NEW:
=> Fix tab behaviour when deleting

src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/logic/parser/ViewCommandParser.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java
=> Allow view all command

src/main/java/seedu/address/logic/commands/EditCommand.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java
=> Fix tab behaviour when editing modules

docs/DeveloperGuide.md, src/main/java/seedu/address/logic/parser/DeleteModCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteModTutCommandParser.java
Do let me know if anything needs to be edited
=> DG: Update Appendix: Instructions for manual testing

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/DeleteModCommand.java, src/main/java/seedu/address/logic/commands/DeleteModTutCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java
=> Change duration of help window to 10s

src/main/java/seedu/address/logic/parser/ViewCommandParser.java
=> Change input for module tutorial to uppercase

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
=> Modify edit command to prevent empty module tutorial group

src/main/java/seedu/address/ui/MainWindow.java
=> Fix tab view not updating after commands

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/UserPrefs.java
=> Update logging messages and json file name

src/main/java/seedu/address/logic/commands/AddCommand.java
=> Update Add Duplicate Person Message

src/main/java/seedu/address/logic/commands/DeleteModTutCommand.java, src/main/java/seedu/address/logic/parser/DeleteModTutCommandParser.java, src/main/java/seedu/address/model/person/ModTutGroup.java, src/test/java/seedu/address/logic/commands/DeleteModTutCommandTest.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteModTutCommandParserTest.java
=> Fix delete tutorial throwing exception

src/main/java/seedu/address/model/person/ModTutGroup.java
=> Update empty ModTutGroup message constraints

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/DeleteModCommand.java, src/main/java/seedu/address/logic/commands/DeleteModTutCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Note: Behavior is that any key press will close the popup while also registering the input, but backspace key works differently for some reason, requiring a press to close the popup and a second press to actually delete a character.
I also removed all code relating to isHelp variable.
+15-25 Excluding test cases
closes #297
=> Change popup to close on any keypress instead of timer

src/main/java/seedu/address/model/ModelManager.java
Only issue is that after edit command, the view tabs will leave the filtered view
Added 3 Lines
Closes #324
=> Modify edit behaviour to index correctly

src/main/java/seedu/address/logic/parser/DeleteModCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Module.java
=> Add parseMod

src/main/java/seedu/address/model/person/Email.java, src/test/java/seedu/address/model/person/EmailTest.java
=> Update email REGEX

src/main/java/seedu/address/logic/commands/DeleteModCommand.java, src/main/java/seedu/address/logic/commands/DeleteModTutCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java
=> Change command word to be case-insensitive

src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Name.java
=> Make name and email comparison case insensitive

src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/ModTutGroup.java
=> Fix null pointer exception with delete being first command

src/main/java/seedu/address/MainApp.java
=> Update version number to 1.6

docs/_markbind/layouts/default.md
=> Remove tutorial from website
